# ==========================================
# NOME DA APLICAÇÃO E PORTA
# ==========================================
spring.application.name=deadline
server.port=8080

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (H2 LOCAL)
# ==========================================
# Permite testarmos localmente gravando num arquivo sem precisar instalar o PostgreSQL agora
spring.datasource.url=jdbc:h2:file:./data/empresa-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SEGURANÇA (JWT)
# ==========================================
# Puxa da variável do sistema, mas se não achar (como no seu PC), usa um valor padrão
api.security.token.secret=${JWT_SECRET:senha_falsa_local_apenas_para_desenvolvimento_123}