name: CI Pipeline - Deadline

# Configura para rodar em todo PR para a main ou push direto na main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job de testes do Backend (Spring Boot)
  backend-tests:
    runs-on: ubuntu-latest
    
    # Define a pasta padrão para todos os comandos 'run' deste job
    defaults:
      run:
        working-directory: ./Backend/deadline

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build e Testes do Backend (Maven)
        run: mvn -B clean verify
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

# Teste do Frontend (React) desativados temporariamente,
# pois precisamos configurar o ambiente de testes do React, 
# e isso pode levar um tempo. Assim que estiver configurado, 
# reativaremos essa parte do pipeline. 

#  # Job de testes do Frontend
#  frontend-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout do código
#        uses: actions/checkout@v4
#
#      - name: Configurar Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#          cache: 'npm' # ou 'yarn', 'pnpm'
#
#      - name: Instalar dependências e rodar testes
#        run: |
#          cd Frontend/deadline
#          npm install
#          npm run test